# Generated by Django 3.2.13 on 2022-06-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0002_auto_20220601_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='departMast',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='railwayLocationMaster',
            fields=[
                ('rly_unit_code', models.AutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=10, null=True)),
                ('location_type', models.CharField(max_length=5, null=True)),
                ('location_description', models.CharField(max_length=50)),
                ('parent_location_code', models.CharField(max_length=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=30, null=True)),
                ('station_code', models.CharField(max_length=5, null=True)),
                ('rstype', models.CharField(max_length=15, null=True)),
                ('location_type_desc', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level_Desig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.IntegerField(null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('effectdate', models.CharField(max_length=20, null=True)),
                ('un_officer_id', models.IntegerField(null=True)),
                ('level', models.CharField(max_length=2, null=True)),
                ('designation_code', models.CharField(max_length=15, null=True)),
                ('parent_desig_code', models.CharField(max_length=15, null=True)),
                ('rly_unit', models.CharField(max_length=15, null=True)),
                ('pc7_level', models.CharField(max_length=2, null=True)),
                ('department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.departmast')),
            ],
        ),
        migrations.AddField(
            model_name='departmast',
            name='rly_unit_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.railwaylocationmaster'),
        ),
    ]
