# Generated by Django 3.2.13 on 2022-06-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0003_auto_20220602_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation_Master',
            fields=[
                ('designation_master_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('master_name', models.CharField(max_length=40)),
                ('master_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection_details',
            fields=[
                ('item_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('inspected_on', models.DateTimeField()),
                ('observation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Marked_Officers',
            fields=[
                ('marked_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspection_item_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.inspection_details')),
                ('marked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.designation_master')),
            ],
        ),
    ]
