# Generated by Django 3.2.13 on 2022-06-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0004_designation_master_inspection_details_marked_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='modified_by',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='report_path',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
