# Generated by Django 3.2.13 on 2022-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0005_auto_20220604_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='compliance',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='compliance_recieved_on',
            field=models.DateTimeField(null=True),
        ),
    ]
