# Generated by Django 3.2.13 on 2022-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0007_auto_20220606_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='dept',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='inspection_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
