# Generated by Django 2.0.7 on 2022-06-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0012_auto_20220615_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.CharField(max_length=200)),
                ('delete_flag', models.IntegerField(default=False)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('last_modified_by', models.CharField(max_length=10, null=True)),
                ('last_modified_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection_Checklist',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('checklist_title', models.CharField(max_length=100)),
                ('Inspection_type', models.CharField(choices=[('1', 'Station'), ('2', 'Track'), ('3', 'Workshop'), ('4', 'Gate'), ('5', 'Footplate'), ('6', 'RCD')], default='1', max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('delete_flag', models.IntegerField(default=False)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('last_modified_by', models.CharField(max_length=10, null=True)),
                ('last_modified_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspection_activity',
            name='checklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.Inspection_Checklist'),
        ),
    ]
