# Generated by Django 2.0.7 on 2022-06-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0014_auto_20220620_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_checklist',
            name='inspection_type',
            field=models.IntegerField(choices=[('1', 'Station'), ('2', 'Track'), ('3', 'Workshop'), ('4', 'Gate'), ('5', 'Footplate'), ('6', 'RCD')], default='1'),
        ),
    ]
