# Generated by Django 2.0.7 on 2022-06-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0015_auto_20220628_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_activity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_activity',
            name='last_modified_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_checklist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_checklist',
            name='inspection_type',
            field=models.CharField(choices=[('1', 'Station'), ('2', 'Track'), ('3', 'Workshop'), ('4', 'Gate'), ('5', 'Footplate'), ('6', 'RCD')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='inspection_checklist',
            name='last_modified_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
