# Generated by Django 2.0.7 on 2022-06-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0016_auto_20220628_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_checklist',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
