# Generated by Django 2.0.7 on 2022-06-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0017_auto_20220629_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_activity',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
